# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ios-reddit-challenge' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ios-reddit-challenge

  pod 'Moya'

  target 'ios-reddit-challengeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ios-reddit-challengeUITests' do
    # Pods for testing
  end

end
